import React, { Component } from 'react';
import { NavBar, Icon, Tabs,Carousel } from 'antd-mobile';
const tabs = [
    { title: '推荐'},
    { title: '冬季'},
    { title: '宜家'},
    { title: '小清新'},
    { title: '小户型'},
    { title: '个性色彩'},
  ];
export default class LingGan extends Component {
    
    render() {
        return (  
            <div>
                <NavBar
                    style={{backgroundColor:'#3fcccb',color:'white',height:"6%"}}
                    >灵感</NavBar>
                {<Tabs tabs={tabs}initialPage={0}
                    onChange={(tab, index) => { console.log('onChange', index, tab); }}
                    onTabClick={(tab, index) => { console.log('onTabClick', index, tab); }}
                    >
                    <div style={{backgroundColor: '#fff'}}>
                        <img 
                            src={require("./img/灵感左1.png")}
                            style={{
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感右1.png")}
                            style={{                               
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感左1.png")}
                            style={{
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感右1.png")}
                            style={{                               
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感左1.png")}
                            style={{
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感右1.png")}
                            style={{                               
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感左1.png")}
                            style={{
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感右1.png")}
                            style={{                               
                                height:"50%",
                                width:"50%",
                            }}
                        />
                    </div>
                    <div style={{backgroundColor: '#fff' }}>
                        <img 
                            src={require("./img/灵感右1.png")}
                            style={{                               
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感左1.png")}
                            style={{
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感右1.png")}
                            style={{                               
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感左1.png")}
                            style={{
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感右1.png")}
                            style={{                               
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感左1.png")}
                            style={{
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感右1.png")}
                            style={{                               
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感左1.png")}
                            style={{
                                height:"50%",
                                width:"50%",
                            }}
                        />
                    </div>
                    <div style={{backgroundColor: '#fff' }}>
                        <img 
                            src={require("./img/灵感左1.png")}
                            style={{
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感右1.png")}
                            style={{                               
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感左1.png")}
                            style={{
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感右1.png")}
                            style={{                               
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感左1.png")}
                            style={{
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感右1.png")}
                            style={{                               
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感左1.png")}
                            style={{
                                height:"50%",
                                width:"50%",
                            }}
                        />
                        <img 
                            src={require("./img/灵感右1.png")}
                            style={{                               
                                height:"50%",
                                width:"50%",
                            }}
                        />
                    </div>
                </Tabs>}
            </div>
        )
    }
}
